name = "genomecost-tracker"
compatibility_date = "2024-01-15"

[build]
command = "cd frontend && npm install && npm run build"
destination = "frontend/dist/genomecost-frontend"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200